# Generated by Django 5.1.3 on 2024-12-06 09:29

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='category',
        ),
        migrations.AddField(
            model_name='application',
            name='categories',
            field=models.ManyToManyField(to='main.category'),
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='applications/', validators=[main.models.validate_image]),
        ),
    ]
