# Generated by Django 5.1.3 on 2024-12-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categorystatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
